// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "body_complete_sp_arab_regular_asad";
	a[1] = "body_complete_sp_arab_regular_sadiq";
	a[2] = "body_complete_sp_arab_regular_suren";
	return a;
}
