// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{

	character\character_mp_opforce_urban_engineer::main();
}

precache()
{
	character\character_mp_opforce_urban_engineer::precache();
}
