// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("character_us_cod3_axis_ac130");
	self.voice = "american";
}

precache()
{
	precacheModel("character_us_cod3_axis_ac130");
}
