// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_sp_opforce_a");
	self attach("head_sp_opforce_ski_mask_body_a", "", true);
	self.voice = "russian";
}

precache()
{
	precacheModel("body_sp_opforce_a");
	precacheModel("head_sp_opforce_ski_mask_body_a");
}
