// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_mp_opforce_assault");
	self attach("head_mp_opforce_headwrap", "", true);
	self setViewmodel("viewhands_op_force");
	self.voice = "russian";
}

precache()
{
	precacheModel("body_mp_opforce_assault");
	precacheModel("head_mp_opforce_headwrap");
	precacheModel("viewhands_op_force");
}
