// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_sp_spetsnaz_boris");
	self attach("head_sp_spetsnaz_boris_borisbody", "", true);
	self.voice = "russian";
}

precache()
{
	precacheModel("body_sp_spetsnaz_boris");
	precacheModel("head_sp_spetsnaz_boris_borisbody");
}
