// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_mp_usmc_woodland_sniper");
	self attach("head_mp_usmc_ghillie", "", true);
	self setViewmodel("viewhands_marine_sniper");
	self.voice = "british";
}

precache()
{
	precacheModel("body_mp_usmc_woodland_sniper");
	precacheModel("head_mp_usmc_ghillie");
	precacheModel("viewhands_marine_sniper");
}
