// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_mp_usmc_sniper");
	self attach("head_mp_usmc_tactical_baseball_cap", "", true);
	self setViewmodel("viewmodel_base_viewhands");
	self.voice = "american";
}

precache()
{
	precacheModel("body_mp_usmc_sniper");
	precacheModel("head_mp_usmc_tactical_baseball_cap");
	precacheModel("viewmodel_base_viewhands");
}
