// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_mp_usmc_woodland_assault");
	self attach("head_mp_usmc_tactical_mich", "", true);
	self setViewmodel("viewhands_sas_woodland");
	self.voice = "british";
}

precache()
{
	precacheModel("body_mp_usmc_woodland_assault");
	precacheModel("head_mp_usmc_tactical_mich");
	precacheModel("viewhands_sas_woodland");
}
