// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_mp_sas_urban_support");
	self setViewmodel("viewhands_black_kit");
	self.voice = "british";
}

precache()
{
	precacheModel("body_mp_sas_urban_support");
	precacheModel("viewhands_black_kit");
}
