// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_sp_sas_woodland_assault_a");
	self attach("head_sp_sas_woodland_todd", "", true);
	self.voice = "british";
}

precache()
{
	precacheModel("body_sp_sas_woodland_assault_a");
	precacheModel("head_sp_sas_woodland_todd");
}
