// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_sp_opforce_c");
	self attach("head_sp_opforce_david_beanie_body_c", "", true);
	self.voice = "russian";
}

precache()
{
	precacheModel("body_sp_opforce_c");
	precacheModel("head_sp_opforce_david_beanie_body_c");
}
