// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_mp_arab_regular_cqb");
	self attach("head_mp_arab_regular_headwrap", "", true);
	self setViewmodel("viewhands_desert_opfor");
	self.voice = "arab";
}

precache()
{
	precacheModel("body_mp_arab_regular_cqb");
	precacheModel("head_mp_arab_regular_headwrap");
	precacheModel("viewhands_desert_opfor");
}
