// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_complete_sp_arab_regular_al_asad_dmg");
	self.voice = "arab";
}

precache()
{
	precacheModel("body_complete_sp_arab_regular_al_asad_dmg");
}
