// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_sp_usmc_james");
	self attach("head_sp_usmc_james_james_body_nod", "", true);
	self.voice = "american";
}

precache()
{
	precacheModel("body_sp_usmc_james");
	precacheModel("head_sp_usmc_james_james_body_nod");
}
