// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_complete_gimp_sp_zakhaev");
	self.voice = "russian";
}

precache()
{
	precacheModel("body_complete_gimp_sp_zakhaev");
}
