// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_complete_sp_spetsnaz_boris_sp_ac130");
	self.voice = "russian";
}

precache()
{
	precacheModel("body_complete_sp_spetsnaz_boris_sp_ac130");
}
