// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_complete_sp_usmc_ghillie_price");
	self.voice = "american";
}

precache()
{
	precacheModel("body_complete_sp_usmc_ghillie_price");
}
