// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_sp_opforce_b");
	self attach("head_sp_opforce_3hole_ski_mask_body_b", "", true);
	self.voice = "russian";
}

precache()
{
	precacheModel("body_sp_opforce_b");
	precacheModel("head_sp_opforce_3hole_ski_mask_body_b");
}
