// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_mp_usmc_woodland_support");
	self attach("head_mp_usmc_shaved_head", "", true);
	self setViewmodel("viewhands_sas_woodland");
	self.voice = "british";
}

precache()
{
	precacheModel("body_mp_usmc_woodland_support");
	precacheModel("head_mp_usmc_shaved_head");
	precacheModel("viewhands_sas_woodland");
}
