// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_mp_opforce_support");
	self attach("head_mp_opforce_3hole_mask", "", true);
	self setViewmodel("viewhands_op_force");
	self.voice = "russian";
}

precache()
{
	precacheModel("body_mp_opforce_support");
	precacheModel("head_mp_opforce_3hole_mask");
	precacheModel("viewhands_op_force");
}
