// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_complete_sp_sas_ct_charles");
	self.voice = "british";
}

precache()
{
	precacheModel("body_complete_sp_sas_ct_charles");
}
