// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_complete_sp_cobra_pilot_woodland_zack");
	self.voice = "american";
}

precache()
{
	precacheModel("body_complete_sp_cobra_pilot_woodland_zack");
}
