// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_mp_opforce_cqb");
	self attach("head_mp_opforce_gasmask", "", true);
	self setViewmodel("viewhands_op_force");
	self.voice = "russian";
}

precache()
{
	precacheModel("body_mp_opforce_cqb");
	precacheModel("head_mp_opforce_gasmask");
	precacheModel("viewhands_op_force");
}
