// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_sp_russian_loyalist_b_dead");
	self attach("head_sp_loyalist_mackey_hat_body_b_dead", "", true);
	self.voice = "russian";
}

precache()
{
	precacheModel("body_sp_russian_loyalist_b_dead");
	precacheModel("head_sp_loyalist_mackey_hat_body_b_dead");
}
