// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("sp_usmc_force_mark_no_helmet");
	self.voice = "british";
}

precache()
{
	precacheModel("sp_usmc_force_mark_no_helmet");
}
