// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_sp_sas_woodland_support_a");
	self attach("head_sp_sas_woodland_hugh", "", true);
	self.voice = "british";
}

precache()
{
	precacheModel("body_sp_sas_woodland_support_a");
	precacheModel("head_sp_sas_woodland_hugh");
}
