// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_sp_russian_loyalist_d");
	self attach("head_sp_loyalist_tom_hat_body_d", "", true);
	self.voice = "russian";
}

precache()
{
	precacheModel("body_sp_russian_loyalist_d");
	precacheModel("head_sp_loyalist_tom_hat_body_d");
}
