// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_sp_russian_loyalist_a_dead");
	self attach("head_sp_loyalist_alex_helmet_body_a_dead", "", true);
	self.voice = "russian";
}

precache()
{
	precacheModel("body_sp_russian_loyalist_a_dead");
	precacheModel("head_sp_loyalist_alex_helmet_body_a_dead");
}
