// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_sp_opforce_f");
	self attach("head_sp_opforce_gas_mask_body_f", "", true);
	self.voice = "russian";
}

precache()
{
	precacheModel("body_sp_opforce_f");
	precacheModel("head_sp_opforce_gas_mask_body_f");
}
