// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_sp_spetsnaz_vlad");
	self attach("head_sp_spetsnaz_collins_vladbody", "", true);
	self.voice = "russian";
}

precache()
{
	precacheModel("body_sp_spetsnaz_vlad");
	precacheModel("head_sp_spetsnaz_collins_vladbody");
}
