// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_sp_arab_regular_asad");
	self attach("head_sp_arab_regular_ski_mask", "", true);
	self.voice = "arab";
}

precache()
{
	precacheModel("body_sp_arab_regular_asad");
	precacheModel("head_sp_arab_regular_ski_mask");
}
