// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_mp_arab_regular_sniper");
	self attach("head_mp_arab_regular_sadiq", "", true);
	self setViewmodel("viewhands_desert_opfor");
	self.voice = "arab";
}

precache()
{
	precacheModel("body_mp_arab_regular_sniper");
	precacheModel("head_mp_arab_regular_sadiq");
	precacheModel("viewhands_desert_opfor");
}
