// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	codescripts\character::setModelFromArray(xmodelalias\alias_sp_arab_regular::main());
	self.voice = "arab";
}

precache()
{
	codescripts\character::precacheModelArray(xmodelalias\alias_sp_arab_regular::main());
}
