// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_complete_sp_zakhaevs_son");
	self.voice = "russian";
}

precache()
{
	precacheModel("body_complete_sp_zakhaevs_son");
}
