// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("character_arab_civilian_lowres_c");
	self.voice = "arab";
}

precache()
{
	precacheModel("character_arab_civilian_lowres_c");
}
