// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_sp_russian_loyalist_d_dead");
	self attach("head_sp_loyalist_tom_hat_body_d_dead", "", true);
	self.voice = "russian";
}

precache()
{
	precacheModel("body_sp_russian_loyalist_d_dead");
	precacheModel("head_sp_loyalist_tom_hat_body_d_dead");
}
