// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_sp_opforce_e");
	self attach("head_sp_opforce_justin_beanie_body_e", "", true);
	self.voice = "russian";
}

precache()
{
	precacheModel("body_sp_opforce_e");
	precacheModel("head_sp_opforce_justin_beanie_body_e");
}
