// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_sp_russian_loyalist_c");
	self attach("head_sp_loyalist_josh_helmet_body_c", "", true);
	self.voice = "russian";
}

precache()
{
	precacheModel("body_sp_russian_loyalist_c");
	precacheModel("head_sp_loyalist_josh_helmet_body_c");
}
