// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_sp_spetsnaz_demetry");
	self attach("head_sp_spetsnaz_demetry_demetrybody", "", true);
	self.voice = "russian";
}

precache()
{
	precacheModel("body_sp_spetsnaz_demetry");
	precacheModel("head_sp_spetsnaz_demetry_demetrybody");
}
