// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_mp_usmc_recon");
	self attach("head_mp_usmc_nomex", "", true);
	self setViewmodel("viewmodel_base_viewhands");
	self.voice = "american";
}

precache()
{
	precacheModel("body_mp_usmc_recon");
	precacheModel("head_mp_usmc_nomex");
	precacheModel("viewmodel_base_viewhands");
}
