// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_sp_sas_woodland_at4");
	self attach("head_sp_sas_woodland_mac", "", true);
	self.voice = "british";
}

precache()
{
	precacheModel("body_sp_sas_woodland_at4");
	precacheModel("head_sp_sas_woodland_mac");
}
