// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_specops_sp");
	self attach("head_specops_sp", "", true);
	self.voice = "american";
}

precache()
{
	precacheModel("body_specops_sp");
	precacheModel("head_specops_sp");
}
