// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_complete_sp_sas_nvg_price");
	self.voice = "british";
}

precache()
{
	precacheModel("body_complete_sp_sas_nvg_price");
}
