// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_sp_arab_regular_yasir");
	self attach("head_sp_arab_regular_mowrap", "", true);
	self.voice = "arab";
}

precache()
{
	precacheModel("body_sp_arab_regular_yasir");
	precacheModel("head_sp_arab_regular_mowrap");
}
