// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_mp_opforce_sniper_urban");
	self attach("head_mp_opforce_justin", "", true);
	self setViewmodel("viewhands_op_force");
	self.voice = "russian";
}

precache()
{
	precacheModel("body_mp_opforce_sniper_urban");
	precacheModel("head_mp_opforce_justin");
	precacheModel("viewhands_op_force");
}
