// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_sp_spetsnaz_yuri");
	self attach("head_sp_spetsnaz_geoff_yuribody", "", true);
	self.voice = "russian";
}

precache()
{
	precacheModel("body_sp_spetsnaz_yuri");
	precacheModel("head_sp_spetsnaz_geoff_yuribody");
}
