#include maps\_anim;
main()
{
    // Autogenerated by AnimSounds. Threaded off so that it can be placed before _load( has to create level.scr_notetrack first ).
    thread init_animsounds();
}

init_animsounds()
{
    waittillframeend;
    addOnStart_animSound( "razorwire_guy", "razor_setup", "armada_wire_drag" ); 
}
