#include maps\_anim;
main()
{
    // Autogenerated by AnimSounds. Threaded off so that it can be placed before _load( has to create level.scr_notetrack first ).
    thread init_animsounds();
}

init_animsounds()
{
    waittillframeend;
    addOnStart_animSound( "tower", "explosion", "scn_icbm_tower_exp_sweet" ); 
}
